# Generated by Django 3.2.8 on 2021-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('group_size', models.IntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
